app:
  build: .
  command: python -u appli.py
  container_name: flask_app
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: test_mongodb
  container_name: mongo
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  volumes:
    - ../data/mongo:/data/db
  ports:
    - 27018:27017